name: Deploy CloudWatch Log Archival Infra

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Infra & Lambda
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1
      BUCKET: cw-log-archive-prod

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies (if any)
        run: pip install -r requirements.txt || true

      - name: Zip Lambda
        run: |
          cd lambda
          zip -r9 ../lambda.zip ./*
          cd ..

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
